start /wait cmd /c universalv1 ShipHulls_Abandoned
start /wait cmd /c universalv1 Shiphulls_Ackdarian
start /wait cmd /c universalv1 ShipHulls_Boskara
start /wait cmd /c universalv1 ShipHulls_CrazedHiveInsectoids
start /wait cmd /c universalv1 ShipHulls_Dhayut
start /wait cmd /c universalv1 ShipHulls_Gizurean
start /wait cmd /c universalv1 ShipHulls_Haakonish
start /wait cmd /c universalv1 ShipHulls_Human
start /wait cmd /c universalv1 ShipHulls_Ikkuro
start /wait cmd /c universalv1 ShipHulls_Mortalen
start /wait cmd /c universalv1 ShipHulls_Pirates1
start /wait cmd /c universalv1 ShipHulls_Pirates2
start /wait cmd /c universalv1 ShipHulls_Pirates3
start /wait cmd /c universalv1 ShipHulls_Pirates4
start /wait cmd /c universalv1 ShipHulls_PlanetDestroyer
start /wait cmd /c universalv1 ShipHulls_Quameno
start /wait cmd /c universalv1 ShipHulls_Teekan
start /wait cmd /c universalv1 ShipHulls_Zenox